Repository Yawn-Wider/YWPolarisVore, pull requests merged in 2020-04, with the labels that each got.

#679 Fixes phorochemistry messages to use to_chat
  code/modules/Phorochemistry/phororeagent.dm
Labels: enhancement

#681 [FIX] Fix minor issue in SDF interception event
  code/modules/busy_space_yw/air_traffic.dm
Labels: enhancement

#682 [FIX] Simplemob grabs w/ lacertusol
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: enhancement

#674 [Earlyport] Mutable Emotes
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_vr.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/emote_vr.dm
Labels: enhancement

#683 [TWEAK] Conversion Kit Overhaul
  code/modules/vore/fluffstuff/custom_items_vr.dm
  code/modules/vore/fluffstuff/custom_items_yw.dm
  code/modules/vore/fluffstuff/custom_rigs_yw.dm
Labels: enhancement

#692 First Blueshield Access Pass
  code/game/machinery/doors/airlock_yw.dm
  maps/yw/cryogaia-04-maintenance.dmm
  maps/yw/cryogaia-05-main.dmm
  vorestation.dme
Labels: enhancement

#653 Setup for Chem-Traits
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine_vr.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Labels: enhancement

#702 Adds new autolathe interface for testing before sending to polaris/virgo
  code/__defines/research.dm
  code/datums/autolathe/arms_1.dm
  code/datums/autolathe/arms_1_vr.dm
  code/datums/autolathe/arms_1_yw.dm
  code/datums/autolathe/autolathe_yw.dm
  code/datums/autolathe/devices_1.dm
  code/datums/autolathe/devices_1_vr.dm
  code/datums/autolathe/engineering_1.dm
  code/datums/autolathe/engineering_1_vr.dm
  code/datums/autolathe/general_1.dm
  code/datums/autolathe/general_1_vr.dm
  code/datums/autolathe/medical_1.dm
  code/datums/autolathe/medical_1_vr.dm
  code/datums/autolathe/tools_1.dm
  code/datums/autolathe/tools_1_vr.dm
  code/datums/autolathe/tools_1_yw.dm
  code/modules/power/tesla/telsa_construction.dm
  code/modules/research/designs.dm
  nano/templates/autolathe.tmpl
  vorestation.dme
Labels: enhancement

#714 makes hand plush do noise when poked too
  code/game/objects/items/toys.dm
Labels: enhancement

#715 Updates residential to have spawn point elevator area thing
  maps/yw/cryogaia_defines.dm
  maps/yw/residential/_residential.dm
  maps/yw/residential/residential.dmm
Labels: enhancement

#713 Mapfixes Pass (Part 1)
  icons/turf/areas_yw.dmi
  maps/yw/cryogaia-04-maintenance.dmm
  maps/yw/cryogaia-05-main.dmm
  maps/yw/cryogaia_areas.dm
Labels: bug fix

#719 Sec Voidsuit Sync
  code/datums/supplypacks/voidsuits.dm
  code/modules/clothing/spacesuits/void/station.dm
Labels: enhancement, upstream

#717 Unique S/H Cell Icons
  code/modules/power/cells/device_cells.dm
  icons/obj/power_yw.dmi
Labels: enhancement

#722 [EARLYPORT] Nightstalker Tail~
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
Labels: enhancement, upstream

#721 Adds purchaseable Piano crates to cargo
  code/datums/supplypacks/recreation_yw.dm
  code/game/objects/structures/crates_lockers/largecrate_yw.dm
  vorestation.dme
Labels: enhancement

#723 Tesh suits resync
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
  icons/obj/clothing/species/seromi/hats.dmi
  icons/obj/clothing/species/seromi/suits.dmi
Labels: bug fix

#718 Autolathe fixes
  code/__defines/research.dm
  code/datums/autolathe/arms_1.dm
  code/datums/autolathe/autolathe_yw.dm
  code/datums/autolathe/general_1.dm
Labels: bug fix
