Repository Yawn-Wider/YWPolarisVore, pull requests merged in 2020-05, with the labels that each got.

#728 Fixes autolathe recipes in Prosthetics machine and adds missing recipes+buildable teleporter
  code/__defines/research.dm
  code/datums/autolathe/arms_1.dm
  code/datums/autolathe/devices_1.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/modules/research/designs/circuits/circuits_yw.dm
  vorestation.dme
Labels: enhancement

#732 Mapfixes Pass (Part 2)
  code/game/jobs/access_datum_yw.dm
  maps/yw/cryogaia-05-main.dmm
  maps/yw/cryogaia_jobs.dm
  maps/yw/structures/closets/misc.dm
  maps/yw/structures/closets/misc_vr.dm
  vorestation.dme
Labels: enhancement

#734 orders the NT cheap knockoff breacher chassis instead
  code/datums/supplypacks/voidsuits.dm
Labels: enhancement

#665 [JOB/ACCESS] Security Pilot
  code/datums/outfits/jobs/security_yw.dm
  code/game/jobs/access_datum_yw.dm
  code/game/jobs/job/security_yw.dm
  code/game/jobs/jobs.dm
  code/game/objects/structures/crates_lockers/closets/secure/closets_yw.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_accessories_vr.dm
  code/modules/client/preference_setup/loadout/loadout_accessories_yw.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_eyes_yw.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_uniform_vr.dm
  code/modules/client/preference_setup/loadout/loadout_uniform_yw.dm
  code/modules/client/preference_setup/loadout/loadout_utility_vr.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/under/extrauniforms_yw.dm
  icons/obj/closet_yw.dmi
  vorestation.dme
Labels: enhancement

#735 Security Interceptor
  icons/mob/hud_jobs_vr.dmi
  maps/yw/cryogaia-05-main.dmm
  maps/yw/cryogaia_areas.dm
  maps/yw/cryogaia_defines.dm
  maps/yw/cryogaia_shuttles.dm
Labels: enhancement

#738 Engineering Workshop Access Fix & Trader Pad Line Fix
  maps/yw/cryogaia-05-main.dmm
Labels: bug fix

#736 Scattershot Speedloaders & Ammobox Printing
  code/datums/autolathe/arms_1_yw.dm
  code/modules/projectiles/ammunition/magazines_yw.dm
  icons/obj/ammo_yw.dmi
  vorestation.dme
Labels: enhancement

#741 Keyboard fixes+Interceptor adjustments
  code/game/objects/items/devices/instruments.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets_yw.dm
  icons/obj/closet_yw.dmi
  maps/yw/cryogaia-05-main.dmm
  maps/yw/scratchmap.dmm
  vorestation.dme
Labels: bug fix, enhancement

#739 Adds disabilities tab on general for disabilities any species can have
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences_vr.dm
  code/modules/client/preferences_yw.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
  vorestation.dme
Labels: enhancement

#742 Re-adds missing icon
  icons/obj/closet_yw.dmi
Labels: bug fix

#753 Fixes Sec Pilots not getting PTO
  code/game/jobs/job/security_yw.dm
Labels: bug fix

#744 Interceptor/Security Refinements, pt1
  code/game/jobs/job/security_yw.dm
  code/game/objects/structures/crates_lockers/closets/secure/closets_yw.dm
  maps/yw/cryogaia-05-main.dmm
  maps/yw/submaps/beach/_beach.dm
  maps/yw/submaps/beach/beach.dmm
Labels: enhancement

#752 Vulp Hazard Hardsuits
  icons/mob/species/vulpkanin/helmet.dmi
  icons/mob/species/vulpkanin/suit.dmi
Labels: upstream

#747 Fix for Resetting Character Slot
  code/modules/client/preferences_savefile.dm
Labels: upstream

#743 makes travis man not angry + disk functionality into autolathe
  code/datums/autolathe/arms_1.dm
  code/datums/autolathe/autolathe_yw.dm
  code/datums/autolathe/engineering_1.dm
  code/modules/research/designs.dm
  code/modules/research/designs/weapons.dm
Labels: bug fix, enhancement

#754 Fixes cloaks bugging after dropped and updates seromi collar sprite state_name
  code/modules/clothing/under/accessories/clothing.dm
  icons/obj/clothing/collars_seromi_yw.dmi
Labels: bug fix

#746 Recoil knockdown code for micros
  code/modules/projectiles/gun.dm
Labels: enhancement

#755 Fixes jobs
  maps/yw/cryogaia_jobs.dm
  vorestation.dme
Labels: bug fix

#757 Mapfixes Pass III: Camera Networks
  code/__defines/machinery.dm
  code/game/jobs/access_datum_yw.dm
  code/game/machinery/camera/presets.dm
  maps/yw/cryogaia-02-mining.dmm
  maps/yw/cryogaia-04-maintenance.dmm
  maps/yw/cryogaia-05-main.dmm
  maps/yw/cryogaia_defines.dm
  maps/yw/cryogaia_jobs.dm
  maps/yw/structures/closets/misc.dm
Labels: enhancement

#759 Updates booring cyborg and travis
  .github/boring-cyborg.yml
  tools/travis/compile_and_run.sh
Labels: Type: .git or .github

#762 Mapfixes Pt IIIa
  code/game/machinery/camera/presets.dm
  maps/yw/cryogaia-02-mining.dmm
  maps/yw/cryogaia-04-maintenance.dmm
  maps/yw/cryogaia-05-main.dmm
Labels: bug fix

#763 Update boring-cyborg.yml
  .github/boring-cyborg.yml
Labels: Type: .git or .github

#767 Updates encryptionkey_vr.dm
  code/game/objects/items/devices/radio/encryptionkey_vr.dm
Labels: Type: Vore

#771 adds RPED sprite in hand
  code/defines/obj/weapon.dm
  icons/vore/custom_items_left_hand_yw.dmi
  icons/vore/custom_items_right_hand_yw.dmi
Labels: Type: Fluff, Type: Icon

#770 Adds back the 'Hunter' net gun as a new type
  code/modules/projectiles/guns/energy/netgun_vr.dm
  code/modules/projectiles/guns/energy/netgun_yw.dm
  code/modules/research/designs/weapons_vr.dm
  code/modules/research/designs/weapons_yw.dm
  vorestation.dme
Labels: Type: Vore, enhancement

#773 Finishes the sound additions
  code/controllers/emergency_shuttle_controller.dm
  code/controllers/subsystems/ticker.dm
  code/modules/shuttles/shuttle_emergency.dm
  sound/AI/yawn/shuttle_arrive.ogg
  sound/AI/yawn/shuttle_called.ogg
  sound/AI/yawn/shuttle_depart.ogg
  sound/AI/yawn/welcome.ogg
Labels: Type: Sound

#777 Misc Minor Fixes
  code/game/jobs/job/science_vr.dm
  maps/yw/cryogaia-01-centcomm.dmm
  maps/yw/cryogaia-02-mining.dmm
  maps/yw/cryogaia-04-maintenance.dmm
  maps/yw/cryogaia-05-main.dmm
Labels: Type: Map, Type: Vore, bug fix

#778 Fax and original lore shis.
  code/_helpers/time.dm
  code/datums/outfits/outfit_vr.dm
  code/game/objects/banners_vr.dm
  code/game/objects/effects/decals/posters/polarisposters_vr.dm
  code/global.dm
  code/modules/clothing/head/misc_vr.dm
  code/modules/clothing/head/solgov_vr.dm
  code/modules/clothing/suits/armor_vr.dm
  code/modules/clothing/suits/miscellaneous_vr.dm
  code/modules/clothing/suits/solgov_vr.dm
  code/modules/clothing/under/accessories/permits_vr.dm
  code/modules/clothing/under/miscellaneous_vr.dm
  code/modules/clothing/under/solgov_vr.dm
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
  code/modules/paperwork/faxmachine.dm
Labels: Type: Vore

#781 Activates AI multicam on Cryogaia.
  maps/yw/cryogaia-01-centcomm.dmm
Labels: Type: Map, enhancement

#782 makes lathes not go poof when they work.
  icons/obj/machines/research_vr.dmi
Labels: Type: Icon, Type: Vore, bug fix

#784 Voreupdate
  code/__defines/_planes+layers.dm
  code/__defines/turfs.dm
  code/_helpers/turfs.dm
  code/datums/outfits/outfit_vr.dm
  code/datums/uplink/visible_weapons_vr.dm
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/objects/effects/decals/posters/voreposters_vr.dm
  code/game/objects/items/devices/scanners_vr.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/medical_vr.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/window.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/floor_types_eris.dm
  code/modules/client/client procs.dm
  code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
  code/modules/clothing/head/solgov_vr.dm
  code/modules/clothing/suits/solgov.dm
  code/modules/clothing/suits/solgov_vr.dm
  code/modules/clothing/under/solgov_vr.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  code/modules/projectiles/ammunition/magazines_vr.dm
  code/modules/projectiles/ammunition/magnetic.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun_vr.dm
  code/modules/projectiles/projectile/bullets_vr.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/research/rdmachines.dm
  config/alienwhitelist.txt
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/contraband_vr.dmi
  icons/obj/projectiles.dmi
  icons/obj/railgun.dmi
  icons/obj/stacks_vr.dmi
  maps/tether/submaps/admin_use/fun.dm
  maps/tether/submaps/offmap/talon1.dmm
  maps/tether/submaps/offmap/talon2.dmm
  maps/tether/submaps/om_ships/aro2.dm
  maps/tether/submaps/om_ships/aro2.dmm
  maps/tether/tether-02-surface2.dmm
  maps/tether/tether-03-surface3.dmm
  maps/tether/tether-04-transit.dmm
  maps/tether/tether-07-station3.dmm
  vorestation.dme
Labels: Type: Vore, upstream
