Repository Yawn-Wider/YWPolarisVore, pull requests merged in 2020-09, with the labels that each got.

#997 Fixes some M << to to_chat references.
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_yw.dm
  code/modules/power/power.dm
  code/modules/reagents/kelshark.dm
  code/modules/vore/fluffstuff/MadokaSpear.dm
Labels: bug fix

#999 re-adds setckey command
  code/modules/admin/admin_verb_lists.dm
  code/modules/admin/ckey_vr.dm
Labels: Type: Vore, enhancement

#998 Xenobotany Expansion: Biochemical Manipulator
  code/modules/hydroponics/seed_machines_yw.dm
  tgui/packages/tgui/interfaces/PrecisionEditor.js
  tgui/packages/tgui/public/tgui.bundle.js
  vorestation.dme
Labels: enhancement

#1000 adjusted the sprite of my custom outfit
  icons/vore/custom_clothes_yw.dmi
Labels: Type: Icon

#1001 Nanomap
  nano/images/nanomap_z2.png
  nano/images/nanomap_z3.png
  nano/images/nanomap_z4.png
  nano/images/nanomap_z5.png
  nano/images/nanomap_z6.png
Labels: Type: Icon

#1004 Fix building new airlocks
  code/game/machinery/doors/airlock.dm
Labels: bug fix

#1005 [RTM] Kbraid.edit/additions (plushi fluff)
  code/game/objects/items/toys/toys_yw.dm
  code/modules/client/preference_setup/loadout/loadout_fluffitems_yw.dm
  icons/mob/items/lefthand_toys_yw.dmi
  icons/mob/items/righthand_toys_yw.dmi
  icons/mob/toy_worn_yw.dmi
  icons/obj/toy_yw.dmi
  icons/vore/custom_clothes_yw_special.dmi
  icons/vore/custom_items_left_hand_yw.dmi
  icons/vore/custom_items_right_hand_yw.dmi
  icons/vore/custom_items_yw.dmi
  icons/vore/custom_onmob_yw.dmi
Labels: Type: Fluff, Type: Icon

#1008 adds rms to workshop
  maps/yw/cryogaia-05-main.dmm
  maps/yw/cryogaia-06-upper.dmm
Labels: Type: Map

#1009 Removes nanoUI autolathe stuff from code and adds recycle functionality into tgui one
  code/__defines/research.dm
  code/datums/autolathe/arms_1.dm
  code/datums/autolathe/arms_1_vr.dm
  code/datums/autolathe/arms_1_yw.dm
  code/datums/autolathe/autolathe_yw.dm
  code/datums/autolathe/devices_1.dm
  code/datums/autolathe/devices_1_vr.dm
  code/datums/autolathe/engineering_1.dm
  code/datums/autolathe/engineering_1_vr.dm
  code/datums/autolathe/general_1.dm
  code/datums/autolathe/general_1_vr.dm
  code/datums/autolathe/medical_1.dm
  code/datums/autolathe/medical_1_vr.dm
  code/datums/autolathe/tools_1.dm
  code/datums/autolathe/tools_1_vr.dm
  code/datums/autolathe/tools_1_yw.dm
  code/game/machinery/autolathe.dm
  code/modules/power/tesla/telsa_construction.dm
  code/modules/research/designs.dm
  code/modules/research/designs/weapons.dm
  nano/templates/autolathe.tmpl
Labels: Type: Vore, enhancement

#1011 Fix stripping.dm cloning bug
  code/modules/mob/living/carbon/human/stripping.dm
Labels: bug fix

#1010 more tesh equip slots
  code/game/objects/items/toys/toys_yw.dm
Labels: enhancement

#1013 added tesh plush ears, fixed PEili not apearing on head.
  code/game/objects/items/toys/toys_yw.dm
  icons/obj/toy_yw.dmi
  icons/vore/custom_items_yw.dmi
Labels: Type: Fluff, Type: Icon

#1015 Missing sprite additions
  icons/mob/species/akula/helmet_vr.dmi
  icons/mob/species/akula/suit_vr.dmi
  icons/mob/species/sergal/helmet_vr.dmi
  icons/mob/species/sergal/suit_vr.dmi
  icons/mob/species/vulpkanin/helmet.dmi
  icons/mob/species/vulpkanin/suit.dmi
  icons/obj/gun.dmi
Labels: Type: Icon, Type: Vore, enhancement

#1014 Cycler changes
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/suit_storage_unit_vr.dm
Labels: Type: Vore, enhancement

#1016 Tesh space suit sprite fix (suit and helmet)
  icons/mob/species/seromi/head.dmi
  icons/mob/species/seromi/suit.dmi
Labels: Type: Icon, enhancement

#1017 Moves arrivals and escape/transfer shuttle to cc z level
  maps/yw/cryogaia-01-centcomm.dmm
  maps/yw/cryogaia-07-misc.dmm
  maps/yw/cryogaia_defines.dm
Labels: Type: Map

#1019 [RTM] KBraid residential room
  code/modules/vore/fluffstuff/custom_furnature_yw.dm
  icons/vore/custom_furniture_yw.dmi
  maps/yw/residential/residential.dmm
  maps/yw/residential/residential_keys.dm
  vorestation.dme
Labels: Type: Icon, Type: Map
