Repository Yawn-Wider/YWPolarisVore, pull requests merged in 2021-01, with the labels that each got.

#1046 Removing spiders, blob and radstorm event temporarily.
  code/modules/events/event_container_vr.dm
Labels: Type: Vore

#1047 Voreupdate
  code/_helpers/unsorted.dm
  code/_onclick/hud/_defines_vr.dm
  code/_onclick/hud/human.dm
  code/controllers/configuration.dm
  code/datums/supplypacks/misc.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/vending_machines.dm
  code/game/objects/items/toys/toys_vr.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/random/misc.dm
  code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin_hud.dm
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_powers.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  code/modules/mob/living/silicon/robot/robot_vr.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines_vr.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/bellymodes_datum_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
  code/modules/vore/fluffstuff/custom_clothes_vr.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  icons/_nanomaps/tether_nanomap_z1.png
  icons/_nanomaps/tether_nanomap_z2.png
  icons/_nanomaps/tether_nanomap_z3.png
  icons/mob/drakeborg/Drakeborg-Licensing.txt
  icons/mob/drakeborg/drakeborg_vr.dmi
  icons/mob/shadekin_hud.dmi
  icons/mob/widerobot_vr.dmi
  icons/obj/drakietoy_vr.dmi
  icons/obj/toy_vr.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/flooring/decals_vr.dmi
  icons/vore/custom_clothes_vr.dmi
  maps/offmap_vr/talon/talon1.dmm
  maps/submaps/admin_use_vr/kk_mercship.dmm
  maps/tether/submaps/tether_misc.dmm
  maps/tether/tether-01-surface1.dmm
  maps/tether/tether-02-surface2.dmm
  maps/tether/tether-03-surface3.dmm
Labels: Type: Icon, Type: Vore, upstream

#1048 Quick fix for broken borg sprites
  code/modules/mob/living/silicon/robot/robot_vr.dm
Labels: Type: Vore, bug fix

#1049 Fix X01 stun projectile
  code/modules/projectiles/guns/energy/nuclear_yw.dm
Labels: bug fix

#1050 Tiny Map update
  maps/yw/cryogaia-05-main.dmm
  maps/yw/submaps/rogue_mines/rogue_mine2.dmm
Labels: Type: Map, bug fix
