Repository Yawn-Wider/YWPolarisVore, pull requests merged in 2023-12, with the labels that each got.

#1331 Fixes player notes / Updates player panel
  code/modules/admin/admin.dm
Labels: bug fix

#1333 Make area jump work even if not specifying a area name
  code/modules/admin/verbs/adminjump.dm
Labels: bug fix

#1335 Fixes notes for moderator
  code/modules/admin/admin.dm
  code/modules/tgui/states/admin.dm
Labels: bug fix

#1337 Readds armalis
  code/modules/mob/living/simple_mob/subtypes/animal/vox.dm
  vorestation.dme
Labels: enhancement

#1338 Updates the wiki path
  README.md
  code/modules/mob/living/carbon/human/species/station/greyYW.dm
  code/modules/mob/living/carbon/human/species/station/prometheans_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/mob/living/carbon/human/species/station/teshari_vr.dm
  code/modules/player_tips_vr/player_tips_list_yw.dm
Labels: Type: Vore

#1339 Revert "Updates the wiki path"
  README.md
  code/modules/mob/living/carbon/human/species/station/greyYW.dm
  code/modules/mob/living/carbon/human/species/station/prometheans_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/mob/living/carbon/human/species/station/teshari_vr.dm
  code/modules/player_tips_vr/player_tips_list_yw.dm
Labels: Type: Vore

#1340 Updates readme and fixes books slightly
  README.md
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/items/weapons/manuals_vr.dm
  code/modules/mob/living/carbon/human/species/station/greyYW.dm
Labels: bug fix, Type: Vore

#1341 Allows mods to also pm
  code/modules/admin/verbs/adminpm.dm
Labels: bug fix

#1342 Vox Armalis QoL
  code/modules/mob/living/simple_mob/subtypes/animal/vox.dm
Labels: bug fix

#1344 a few xmas additions - to revert sometime next year
  maps/yw/cryogaia-04-maintenance.dmm
  maps/yw/cryogaia-05-main.dmm
Labels: enhancement, Type: Map

#1347 Rsffix
  code/game/objects/items/weapons/RSF.dm
Labels: bug fix

#1348 Fixes snowsuits and small tips edit
  code/modules/clothing/head/hood_yw.dm
  code/modules/clothing/head/jobs_yw.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/suits/armor_yw.dm
  code/modules/clothing/suits/hooded_yw.dm
  code/modules/clothing/suits/storage_yw.dm
  code/modules/player_tips_vr/player_tips_list_yw.dm
  icons/inventory/head/item_yw.dmi
  icons/inventory/head/mob_yw.dmi
  icons/inventory/suit/item_yw.dmi
  icons/inventory/suit/mob_yw.dmi
  icons/mob/species/teshari/suit_yw.dmi
  icons/mob/suit_yw.dmi
  icons/obj/clothing/suits_yw.dmi
Labels: bug fix, Type: Vore, Type: Icon

#1349 Annihilates stuff under submaps for trees
  maps/submaps/surface_submaps/plains_yw/plains.dm
Labels: bug fix, Type: Map

#1351 Adds jungle VR map
  maps/expedition_vr/aerostat/surface_yw.dmm
  maps/offmap_vr/common_offmaps.dm
  maps/yw/cryogaia-07-misc.dmm
  maps/yw/cryogaia.dm
  maps/yw/cryogaia_areas.dm
  maps/yw/cryogaia_defines.dm
  maps/yw/submaps/_cryogaia_submaps.dm
  maps/yw/submaps/gateway/carpfarm.dm
  maps/yw/submaps/gateway/carpfarm.dmm
  maps/yw/submaps/gateway/listeningpost.dm
  maps/yw/submaps/gateway/listeningpost.dmm
  maps/yw/submaps/gateway/snow_outpost.dm
  maps/yw/submaps/gateway/snow_outpost.dmm
  maps/yw/submaps/gateway/snowfield.dm
  maps/yw/submaps/gateway/snowfield.dmm
  maps/yw/submaps/gateway/zoo.dm
  maps/yw/submaps/gateway/zoo.dmm
  maps/yw/yw_vrstuff/_vrmaps.dm
  maps/yw/yw_vrstuff/vrmaps.dmm
  maps/yw/yw_vrstuff/vrmaps_turfs.dm
Labels: enhancement, Type: Vore, Type: Map

#1352 bugfix and monsterspawner
  maps/yw/cryogaia.dm
  maps/yw/yw_vrstuff/_vrmaps.dm
  maps/yw/yw_vrstuff/vrmaps.dmm
  maps/yw/yw_vrstuff/vrmaps_things.dm
Labels: enhancement, bug fix, Type: Vore, Type: Map

#1354 Fixes away team encryption keys
  maps/yw/items/encryptionkey_sc.dm
  maps/yw/items/encryptionkey_vr.dm
Labels: Type: Vore

#1355 More jungle vr fix
  maps/yw/yw_vrstuff/_vrmaps.dm
  maps/yw/yw_vrstuff/vrmaps.dmm
  maps/yw/yw_vrstuff/vrmaps_things.dm
Labels: Type: Vore, Type: Map

#1356 Medalfluff and jungle vr map fix
  code/modules/client/preference_setup/loadout/event_fluffitems_yw.dm
  code/modules/clothing/under/accessories/accessory_yw.dm
  vorestation.dme
Labels: Type: Vore, Type: Fluff, Type: Map

#1358 Adds a bird taur sprite named Azrien, offered as public use by pinkkirby
  code/modules/vore/appearance/sprite_accessories_taur_yw.dm
  icons/mob/vore/taurs_yw.dmi
Labels: Type: Icon
